import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "CSE Academic Solutions",
  description: "Generated by All Info Zone ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
